# /qompassai/rust/rustfmt.toml
# Qompass AI Rustfmt Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
brace_style = 'PreferSameLine'
comment_width = 80
condense_wildcard_suffixes = true
edition = '2021'
fn_single_line = true
format_code_in_doc_comments = true
group_imports = 'StdExternalCrate'
reorder_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
