# Stable https://rust-lang.github.io/rustfmt/?version=v1.7.0
use_field_init_shorthand = true
edition = "2021"
newline_style = "Unix"
reorder_imports = true


# Nightly
condense_wildcard_suffixes = true
brace_style = "PreferSameLine"
fn_single_line = true
where_single_line = true
reorder_impl_items = true
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 80
group_imports = "StdExternalCrate"
